import {test} from "vitest";
import assert from "node:assert/strict";
import {
  createPitchGridLines,
  noteNameToCents,
  noteNameToHz,
  PITCH_NOTE_OPTIONS,
} from "../src/pitchScale.js";

test("pitch note options span A0..C8", () => {
  assert.equal(PITCH_NOTE_OPTIONS[0], "A0");
  assert.equal(PITCH_NOTE_OPTIONS[PITCH_NOTE_OPTIONS.length - 1], "C8");
});

test("note name conversion returns expected Hz bounds", () => {
  const c1Hz = noteNameToHz("C1");
  const c7Hz = noteNameToHz("C7");
  assert.ok(Math.abs(c1Hz - 32.7) < 0.5);
  assert.ok(Math.abs(c7Hz - 2093) < 3);
});

test("pitch grid line tiers and labels are generated by note class", () => {
  const minCents = noteNameToCents("C3");
  const maxCents = noteNameToCents("B3");
  const lines = createPitchGridLines({minCents, maxCents});

  assert.equal(lines.length, 12);
  const octaveLines = lines.filter((line) => line.tier === "octave");
  const naturalLines = lines.filter((line) => line.tier === "natural");
  const accidentalLines = lines.filter((line) => line.tier === "accidental");

  assert.equal(octaveLines.length, 1);
  assert.equal(octaveLines[0].noteName, "C3");
  assert.equal(naturalLines.length, 6);
  assert.equal(accidentalLines.length, 5);
  assert.equal(accidentalLines.every((line) => line.showLabel === false), true);
  assert.equal(naturalLines.every((line) => line.showLabel === true), true);
});
